export const foodState = [
  {
    typeof: "Veg",
    amount: 120,
    name: "Veg Manchurian",
    slug: "",
  },
  {
    typeof: "Veg",
    amount: 140,
    name: "Panner Manchurian",
    slug: "",
  },
  {
    typeof: "Veg",
    amount: 60,
    name: "Baby Corn Manchurian",
    slug: "",
  },
  // {
  //   typeof: "Veg",
  //   amount: 60,
  //   name: "Potato Chilly",
  //   slug: "",
  // },
  // {
  //   typeof: "Veg",
  //   amount: 60,
  //   name: "Baby Corn Chilly",
  //   slug: "",
  // },
  // {
  //   typeof: "Veg",
  //   amount: 60,
  //   name: "Mushroom Chilly",
  //   slug: "",
  // },
  {
    typeof: "nonVeg",
    amount: 60,
    name: "Chicken Chilly Bone",
    slug: "",
  },
  {
    typeof: "nonVeg",
    amount: 60,
    name: "Chicken Chilly Boneless",
    slug: "",
  },
  {
    typeof: "nonVeg",
    amount: 60,
    name: "Chicken Lolipop",
    slug: "",
  },
  // {
  //   typeof: "nonVeg",
  //   amount: 60,
  //   name: "Chicken Crispy",
  //   slug: "",
  // },

  // {
  //   typeof: "Veg",
  //   amount: 60,
  //   name: "Panner Manchurian",
  //   slug: "",
  // },
  // {
  //   typeof: "Veg",
  //   amount: 60,
  //   name: "Veg Manchurian",
  //   slug: "",
  // },
  // {
  //   typeof: "Veg",
  //   amount: 40,
  //   name: "Veg Spring Roll",
  //   slug: "",
  // },
  // {
  //   typeof: "Veg",
  //   amount: 120,
  //   name: "Panner Roll",
  //   slug: "",
  // },
  // {
  //   typeof: "Veg",
  //   amount: 120,
  //   name: "Veg Chowmin",
  //   slug: "",
  // },
  // {
  //   typeof: "Veg",
  //   amount: 120,
  //   name: "Panner Chowmin",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 120,
  //   name: "Egg Chowmin",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 90,
  //   name: "Chicken Chowmin",
  //   slug: "",
  // },
  // {
  //   typeof: "Veg",
  //   amount: 90,
  //   name: "Panner Tikka",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 90,
  //   name: "Chicken Tandoori Full",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 90,
  //   name: "Chicken Tandoori Half",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 90,
  //   name: "Chicken Leg Kebab",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 90,
  //   name: "Chicken Seek Kebab",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 90,
  //   name: "Chicken Tika",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 90,
  //   name: "Panner Seek Tikka",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 90,
  //   name: "Egg biryani",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 140,
  //   name: "Chicken Biryani",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 140,
  //   name: "Single Egg Roll",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 140,
  //   name: "Double Egg Roll",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 140,
  //   name: "Chicken Roll",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 140,
  //   name: "Chicken Single Egg Roll",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 140,
  //   name: "Chicken Double Egg Roll",
  //   slug: "",
  // },
  // {
  //   typeof: "nonVeg",
  //   amount: 60,
  //   name: "Chicken Manchurian",
  //   slug: "",
  // },
];
